### PR TITLE
psfStarChooser: ignore stars near edge & better selection of points

### PR DESCRIPTION
**Pull request by Mikea1985**
Two things: 
- I changed one line so that rather than ignoring stars that are outside the chip, stars are also ignored if they are within moffatWidth+1 from the edge, as including these as "good" stars causes a fatal error. This is a simple fix, so might as well be here rather than rely on the user (especially since psfStarChooser was already checking whether the point was inside the CCD coordinates...). I implemented this because I don't filter for this in my own script, and it's annoying when I miss that one of the postage stamps are only 60 pixels wide rather than 61 and then have to rerun because it crashes. 

- I changed how the the clicking on a star to select if works. Well, how it figures out which star is closest. The delta_x and delta_y between the click and all the points are now scaled by (x_max-x_min) and (y_max-y_max) of the points, so that clicking anywhere should generate delta_x_normed and delta_y_normed between 0 and 1. These values are then added in quadrature to find which point is closest to the click. 

As far as I can tell both work as expected. The star clicking still has some idiosyncrasies (you seem to have to be within a certain distance to select a star, even though I just asked it to select the closest one... I don't really understand why), but it's certainly better than before (no randomly selecting a star that is obviously not the closest).

### CODE REVIEW

**Comment by Mikea1985** [comment]
Well, upon further testing, it seems the clicking part still has idiosyncrasies and does not always highlight the nearest point. I really don't understand why...

**Comment by fraserw** [comment]
Yeah I had tried the simple cartesian distnce thing first. Couldn’t get it to work. 

Rosemary suggested a good option, using the left and right arrow keys to just cycle through the stars displayed, from left to right. That could be implemented without too much work, me thinks. Just haven’t had a chance yet.

**Comment by Mikea1985** [comment]
The pull request should be updated with some new commits. 
I reverted my cartesian conversion and have instead implemented keystrokes for cycling through the points, as per Rosemary's excellent idea. Clicking with the mouse is still an option, but using the keyboard is also.
While I was making significant rewrites to this anyway, I took the opportunity to clean it up a bit where it said "#below should be cleaned up eventually". I also fixed the bug where previously if you had clicked on something, zooming no longer updated the radial plot; now you can zoom and click in whatever order you like. 
Some of the code might not be the best/prettiest (it's 3:30 AM here), but it works, adds functionality and fixes bugs, so that classifies as a success in my book. :-)

**Comment by fraserw** [comment]
This is good stuff. Thanks for the input! Now can you see why I made you
second author?

**Pull request merged**
