### PR TITLE
Fixed errors near edge of chips

### PR DESCRIPTION
**Pull request by Mikea1985**
pill.py: During use I noticed a couple of odd bugs occurring when doing photometry of a target close to the edge of the fields. Three slightly different things happened when: the ignored sky-pill-annulus extends beyond the right (positive x) or bottom (negative y) edge of the image, or when the target is closer than the sky-box width to the left side (ie. x<w). I have fixed these three related bugs and tested; I believe I've fixed them correctly.

psfStarChooser.py:  Unrelated and completely cosmetic. I put the postage stamp over next to the radial distribution, as I want to look at both for each star and it's more convenient having them next to each other.

### CODE REVIEW

**Comment by Mikea1985** [comment]
Something about this you don't like? I can make another pull request without the unrelated cosmetic change to psfStarChooser.py; I realise I should not have lumped that in here. 
I can of course understand if you'd want to test and understand this before implementing, and I would not be surprised if you've just been too busy to do so.

**Comment by fraserw** [comment]
Nope just forgot. Thanks dude! Glad I got you on the project. You and Michael have been quite good at fixing my little things. The edge behaviour was never an issue because the GMOS imagery always had a 200 pixel BG level border. Anyways, thanks. I will test this out in a little while.

BTW - the source subtraction stuff is working really wall. Even on our SNR~50-100 images, with 1 FWHM trailing, they just completely disappear. Finding binaries becomes straight forward!

Wes

**Comment by Mikea1985** [comment]
Yeah, the source subtraction is working quite well. Despite not really needing to do it, I have been doing it anyway as it's nice to see the subtracted images. Also, I often use the centroiding from the MCMC fit instead of from SExtractor for the position used in `phot`, as it often looks more convincingly centred (except when there is nearby background pollution). 

I've found (the obvious result) that the MCMC fit reaches a good fit much faster, if the initial value of `m_in` is closer to final value, so rather than 

```
fitter.fitWithModelPSF(200+xt-int(xt)-1,200+yt-int(yt)-1, m_in=1000.,
```

as you have in the tutorial, I have been using 

```
m_obj=np.max(data[yt-4:yt+5,xt-4:xt+5])
fitter.fitWithModelPSF(200+xt-int(xt)-1,200+yt-int(yt)-1, m_in=m_obj/repFact**2.,
```

(where `repFact` is 10 or whatever has been used everywhere else). This does a nice job almost always. The only time I have issues with the subtraction is when the object is interfering with a bright star or such, because the centroiding gets messed up. But of course, I don't trust the photometry from those images either, so it's not really a big deal.

**Comment by Mikea1985** [comment]
I have yet to see anything that looks like a binary though (I've only done nine objects so far though). Wouldn't binarity screw up the MCMC centroiding?

**Comment by fraserw** [comment]
Nice. BTW if you pass m_in=None, it does an estimate of the initial value
already. I should probably document that...

**Pull request merged**
