### PR TITLE
A couple of new small features and minor cleanup

### PR DESCRIPTION
**Pull request by Mikea1985**
I've added a couple of small features to starChooser that I find helpful. 
The starChooser call now has two new keywords that optionally allows the user to a) show the X, Y, chi, A, B and FWHM values of the selected star on the starChooser plot (example below), and/or b) automatically save the starChooser plot when it is closed. I find these useful for when I've done everything once, realise that a star I accepted actually is bad, and need to redo; this helps identify the correct stars faster. 
best_psfStarChooser
(Unfortunately the saving the plot feature does not function completely reliably; sometimes it fails due to an error that I don't really understand, but I catch the error so that it causes a warning rather than crash entirely.)
I also removed two remaining references to stsci and numdisplay, which we don't use anymore.

### CODE REVIEW

**Comment by Mikea1985** [comment]
I also have code which takes the X-Y coordinates passed out of psfStarChooser to filter the SExtractor catalogue to leave only the good stars; this helps speed up re-running, since I can then just pass in the already filtered SExtractor catalogue and the time-consuming moffat fitting doesn't need to be done on all the stuff I've already determined to be junk once. Would it be desirable to add this as an optional feature directly into psfStarChooser (ie. add a `saveSExCatalogue` keyword, which if true, a SExtractor formatted catalogue of the good stars is automatically saved)?

**Comment by fraserw** [comment]
Could be. How do the stars get saved for rerun?

**Comment by Mikea1985** [comment]
> Could be. How do the stars get saved for rerun?

Actually, sorry, I miss-spoke/miss-remembered. Inside Python it's in the same format as the SExtractor catalogue that was read in (because it's just the SExtractor catalogue filtered to leave only the good lines); I'm not yet actually saving it to a file in the same binary format as the SExtractor catalog file. So for re-run purposes it still needs another read-in mechanism. Never mind, that's not worth folding into starChooser until I've figured out how to save it as a file that looks exactly as if it came from SExtractor.

**Comment by Mikea1985** [comment]
Hi Wes;
I made a bunch more changes. Bug fixes, ensuring python 2.7 and 3.x compatibility, fixes to the tutorial, and a large-ish edit (in terms on number of lines touched): I found the up-to-date, non-deprecated version of zscale in astropy, so I changed everything to use that instead of tzscale, so that we a) use something that actually works (tzscale didn't actually have the masking features implemented that it claimed to have) and b) we don't have to include and maintain a function that was written and abandoned by other people. 
Everything has been tested (by running the tutorial, the test.py file and my own wrapper script) in both Python 2.7 and 3.6; everything looks good (so hopefully I'm introducing fewer new bugs than I fixed :-P)
/Mike

**Comment by fraserw** [comment]
Hi MIke

Thanks for doing some dev work. 
Sounds like we should chat.

I developed tzscale because you specifically asked for it to be included so that we didn’t have to rely on external packages for one single function. Now you’ve changed your mind I guess, and rely on astropy, which is a pretty big package! I am loath to depend on something as big as that again.

What was missing from tzscale? I am confused by your masking statement. The masking is not done in tzscale, the masking is done in the phot call function for photometry. 

Wes

**Comment by fraserw** [comment]
Also, did you read the docs on astropy’s zscale? It is a copy/rework of the stsci zscale. So in essence, is the same function that was abandoned by other people. :)

**Comment by Mikea1985** [comment]
Oh, I didn't realise you had done development on `tzscale`; I thought it was just a verbatim copy of `zscale` from `stsci.numdisplay`. My apologies. A quick glance at the `stsci.numdisplay.zscale` code looked very similar to that of `tzscale`, but I guess I didn't look carefully enough. 
I did look at some of the docs for astropy's zscale, although I looked more at the code to figure out what it's doing. It's more noticeably different from the old `zscale` than `tzscale` is. 

I did consider not wanting dependencies, but we already depend heavily on `astropy`:
`bgfinder.py` uses `astropy.io.fits`
`pill.py` already uses `astropy.visualisation.interval`
`psf.py` seems to optionally use `astropy.io.fits` (or pyfits if astropy.io.fits is not found)
`psfStarChooser.py` uses `astropy.visualization.interval`
So I didn't think adding `astropy.visualization.ZScaleInterval` was a big deal. But if you'd prefer to stick with `tzscale`, I'll re-wind back to that. No problem. 

The masking I'm talking about is related to the `minGoodVal` value; part of `psfStarChooser.starChooser.__init__` calculates a mask (of pixels with values below the `minGoodVal` value), which was previously passed to `tzscale` with the keyword `bpmask=mask`. The doc strings and code of `tzscale` makes it clear that `bpmask` is intended to be a bad pixel mask, but also that use of the mask is not actually implemented.

**Review by fraserw — APPROVED** [review]

**Review by fraserw — APPROVED** [review]

**Review by fraserw — APPROVED** [review]

**Review by fraserw — APPROVED** [review]

**Review by fraserw — APPROVED** [review]

**Review by fraserw — APPROVED** [review]

**Pull request merged**
